### ISSUE TITLE
Missing __init__.py warning when importing pkg_resources

### ISSUE THREAD

**Issue by azmeuk** [zopefoundation/zope.interface#68] opened 2016-12-15 18:09 UTC
Hi. I found that a very simple script can emit an annoying warning about zope.interface. Type this in an empty directory:
``` bash
python2 -m virtualenv env
./env/bin/pip install zope.interface
./env/bin/python -Werror -c "import pkg_resources"
```
The warning produced is:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "./env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "./env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "./env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3047, in _initialize_master_working_set
    for dist in working_set
  File "./env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3047, in <genexpr>
    for dist in working_set
  File "./env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2577, in activate
    declare_namespace(pkg)
  File "./env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2151, in declare_namespace
    _handle_ns(packageName, path_item)
  File "./env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2071, in _handle_ns
    loader = importer.find_module(packageName)
  File "/usr/lib64/python2.7/pkgutil.py", line 186, in find_module
    file, filename, etc = imp.find_module(subname, path)
ImportWarning: Not importing directory './env/lib/python2.7/site-packages/zope': missing __init__.py
```
It is still effective with the current github code `./env/bin/pip install git+https://github.com/zopefoundation/zope.interface.git `

It is a very annoying message since on my django project, it represents 90% of the warnings emitted when I launch my unit tests.

I have tested this with python 2.7.12 and python 3.5.2.

**Comment by icemac** [comment] 2016-12-21 07:13
@azmeuk The missing `__init__.py` exists in the [github repos](https://github.com/zopefoundation/zope.interface/tree/master/src/zope) and in the source distribution on PyPI. But it is missing from the wheel. (Why?)

I can locally (MacOS x 10.11 + Python 2.7.12) reproduce this error with the following versions:

* pip 9.0.1 and 8.1.2
* setuptools 25.4.0, 28.8.1 and 32.1.2
* zope.interface 4.3.3 and Github master

Which version of `setuptools` do you use? Which operating system do you use?

**Comment by azmeuk** [comment] 2016-12-21 08:15
This happened to me on several Linux distributions (Fedora 25, Ubuntu 14.04 and an up-to-data Archlinux). Right now I use my Fedora, and I can reproduce the bug with:
- pip 8.1.2 and 9.0.1
- setuptools 25.1.1 and 32.1.2
- zope.interface 4.3.3 and Github master

**Comment by askoretskiy** [comment] 2016-12-31 16:23
I have exactly the same problem in Docker container.

I have tried check-manifest and generated sdist from source code (4.3.3 tag) -- it includes zope/__init__.py

**Comment by pbrooks** [comment] 2017-01-23 13:53
This issue also presents itself when using Amazon Lambdas, since you're zipping up a virtualenv then the lack of an __init__.py in zope leads to the import not working.

**Comment by ankostis** [comment] 2017-03-02 11:52
I get the same warning on Windows Python-3.5.x.

**Comment by bogdancondurache** [comment] 2017-07-17 09:09
Python 3.6.x and Windows 10 here. I get the same error when trying to compile a project with cx_freeze. Is there any plan for this to be solved in the near future? It seems that only the wheel is missing __init__.py file so it's just a packaging problem.

**Comment by icemac** [comment] 2019-04-18 05:56
According to https://github.com/zopefoundation/zc.lockfile/issues/13 the solution seems to be to upgrade to a newer `setuptools` version which supports PEP 420.

**Comment by jamadden** [comment] 2020-03-17 14:06
Given that current wheels definitely include `zope/interface/__init__.py` and that the referenced setuptools version was released 18 months ago, I think it's safe to close this. Please feel free to re-open if that's not the case.

**Closed by jamadden** 2020-03-17 14:06 UTC
Labels: question
