### ISSUE TITLE
version 4.3.3 breaks py2app

### ISSUE THREAD

**Issue by glyph** [zopefoundation/zope.interface#67] opened 2016-12-14 01:48 UTC
We began seeing this in Mimic in this PR: https://github.com/rackerlabs/mimic/pull/700.

**Comment by glyph** [comment] 2016-12-14 01:48
I reported this against py2app here: https://bitbucket.org/ronaldoussoren/py2app/issues/206/py2app-doesnt-work-with-release-433-of

**Comment by tseaver** [comment] 2016-12-14 03:03
@glyph Thanks for the report.  If the issue is to do with namespace packages, there is a currently-in-work [setuptools issue](https://github.com/pypa/setuptools/issues/885) which may be the source of the problem.

**Comment by glyph** [comment] 2016-12-14 03:15
@tseaver Thanks for the reply. I suspect that is the issue, although I don't know why it would have changed between 4.3.2 and 4.3.3.  Any chance we can drop the 'zope' and just make this 'interface' or 'interfaces'? :) In addition to avoiding the perpetual complexity annoyances of dealing with NS packages (this is not the first time it's broken our mac app build) it would also be a PR coup :).

**Comment by tseaver** [comment] 2016-12-16 12:50
@glyph All renaming aside, did the [setuptools 31.0.1 release](https://setuptools.readthedocs.io/en/latest/history.html#v31-0-1) fix your py2app build?

**Comment by glyph** [comment] 2016-12-16 20:24
We landed a workaround immediately afterwards, and we haven't removed it yet.  However, we have upgraded setuptools, so we could try a PR that removes it...

**Comment by jamadden** [comment] 2020-02-06 16:53
Closing because the upstream issue seems solved and there have been no updates on this for a few years.

**Closed by jamadden** 2020-02-06 16:53 UTC

**Comment by glyph** [comment] 2020-02-07 05:53
Thanks @jamadden !  Ronald's fix did indeed resolve the issue, sorry I didn't follow up.
