### ISSUE TITLE
Failed to install zope.interface

### ISSUE THREAD

**Issue by gloomy-ghost** [zopefoundation/zope.interface#76] opened 2017-03-18 11:00 UTC
```
PS C:\Users\***> pip install zope.interface
Collecting zope.interface
  Using cached zope.interface-4.3.3.tar.gz
Requirement already satisfied: setuptools in c:\users\***\appdata\local\programs\python\python36\lib\site-packages (from zope.interface)
Requirement already satisfied: appdirs>=1.4.0 in c:\users\***\appdata\local\programs\python\python36\lib\site-packages (from setuptools->zope.interface)
Requirement already satisfied: six>=1.6.0 in c:\users\***\appdata\local\programs\python\python36\lib\site-packages (from setuptools->zope.interface)
Requirement already satisfied: packaging>=16.8 in c:\users\***\appdata\local\programs\python\python36\lib\site-packages (from setuptools->zope.interface)
Requirement already satisfied: pyparsing in c:\users\***\appdata\local\programs\python\python36\lib\site-packages (from packaging>=16.8->setuptools->zope.interface)
Installing collected packages: zope.interface
  Running setup.py install for zope.interface ... error
Exception:
Traceback (most recent call last):
  File "c:\users\***\appdata\local\programs\python\python36\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 72: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\***\appdata\local\programs\python\python36\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\***\appdata\local\programs\python\python36\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\users\***\appdata\local\programs\python\python36\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\users\***\appdata\local\programs\python\python36\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "c:\users\***\appdata\local\programs\python\python36\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\users\***\appdata\local\programs\python\python36\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 72: invalid start byte
```

Then I modified pip\compat\__init__.py to print the value that caused UnicodeDecodeError, and it gave:
 ```
b'src\\zope\\interface\\_zope_interface_coptimizations.c(34): warning C4005: \xa1\xb0METH_KEYWORDS\xa1\xb1: \xba\xea\xd6\xd8\xb6\xa8\xd2\xe5\r\n'
```

Is it an issue of zope.interface or pip?

**Comment by tseaver** [comment] 2017-03-18 15:44
Thanks for the report!  I cannot reproduce the issue here:

```bash
$ /opt/Python-2.7.13/bin/virtualenv  /tmp/zi-76-py27
New python executable in /tmp/zi-76-py27/bin/python
Installing setuptools, pip, wheel...done.
$ /tmp/zi-76-py27/bin/pip install --no-cache-dir zope.interface
Collecting zope.interface
  Downloading zope.interface-4.3.3.tar.gz (150kB)
    100% |████████████████████████████████| 153kB 192kB/s 
Requirement already satisfied: setuptools in /tmp/zi-76-py27/lib/python2.7/site-packages (from zope.interface)
Requirement already satisfied: packaging>=16.8 in /tmp/zi-76-py27/lib/python2.7/site-packages (from setuptools->zope.interface)
Requirement already satisfied: appdirs>=1.4.0 in /tmp/zi-76-py27/lib/python2.7/site-packages (from setuptools->zope.interface)
Requirement already satisfied: six>=1.6.0 in /tmp/zi-76-py27/lib/python2.7/site-packages (from setuptools->zope.interface)
Requirement already satisfied: pyparsing in /tmp/zi-76-py27/lib/python2.7/site-packages (from packaging>=16.8->setuptools->zope.interface)
Installing collected packages: zope.interface
  Running setup.py install for zope.interface ... done
Successfully installed zope.interface-4.3.3
$ /opt/Python-3.5.3/bin/python3 -m venv /tmp/zi-76-py35
$ /tmp/zi-76-py35/bin/pip install --no-cache-dir zope.interface
Collecting zope.interface
  Downloading zope.interface-4.3.3.tar.gz (150kB)
    100% |████████████████████████████████| 153kB 137kB/s 
Requirement already satisfied: setuptools in /tmp/zi-76-py35/lib/python3.5/site-packages (from zope.interface)
Installing collected packages: zope.interface
  Running setup.py install for zope.interface ... done
Successfully installed zope.interface-4.3.3
```

There is a recent commit, closing #71, which suppresses that warning.

**Comment by jamadden** [comment] 2017-03-18 18:14
Python 3.6 on Windows [changed the console encoding to utf-8](https://docs.python.org/3/whatsnew/3.6.html#pep-528-change-windows-console-encoding-to-utf-8). That may be why it's only reproducible on that platform.

**Comment by mgedmin** [comment] 2017-03-21 12:10
I'm pretty sure this is a pip problem.

**Closed** 2017-04-19 07:52 UTC
