### ISSUE TITLE
Builds on RTD broken

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.interface#111] opened 2017-12-07 13:38 UTC
According to https://readthedocs.org/projects/zopeinterface/builds/ the builds on RTD are broken for a while. So no changes will show up there.

**Comment by mgedmin** [comment] 2017-12-07 18:55
I can reproduce the build failiure locally with `make -C docs latexpdf`.

**Comment by mgedmin** [comment] 2017-12-08 08:33
Does anyone know how long it usually takes for ReadTheDocs to notice new `master` commits and do a build?

**Comment by mgedmin** [comment] 2017-12-08 09:10
Or maybe @tseaver could give me ReadTheDocs admin access so I can poke around and see what's going on?

**Comment by tseaver** [comment] 2017-12-14 03:02
I just added `mgedmin` as an RTD maintainer.

**Comment by icemac** [comment] 2017-12-14 06:47
@mgedmin wrote:
> Does anyone know how long it usually takes for ReadTheDocs to notice new master commits and do a build?

At least it ran some ours ago but it is still broken. 😢

**Comment by mgedmin** [comment] 2017-12-14 08:46
Maybe it's because we're pinning to an older Sphinx version (1.5.6)?  Or maybe readthedocs hardcodes the use of pdflatex instead of using whichever TeX engine we specified in conf.py?

Meanwhile I unchecked the "Build PDF" checkbox in RTD so we at least get up-to-date HTML docs.

**Comment by mgedmin** [comment] 2017-12-14 08:48
Another problem: the docs built for version 4.4.3 claim they're documenting zope.interface 4.3.4.

**Comment by mgedmin** [comment] 2017-12-14 08:53
> Another problem: the docs built for version 4.4.3 claim they're documenting zope.interface 4.3.4.

Should be fixed in d64c25d.

**Comment by mgedmin** [comment] 2017-12-14 08:56
> Maybe it's because we're pinning to an older Sphinx version (1.5.6)? 

Likely not: the `latex_engine` option was [merged](https://github.com/sphinx-doc/sphinx/commit/f2a7eeca60f681da66104cecc8cba42f62c15226) before Sphinx 1.5.

**Comment by mgedmin** [comment] 2017-12-14 08:58
> Or maybe readthedocs hardcodes the use of pdflatex instead of using whichever TeX engine we specified in conf.py?

[Yup, that's it](https://github.com/rtfd/readthedocs.org/issues/1556#issuecomment-277942883).

**Comment by mgedmin** [comment] 2017-12-14 08:59
I think we can live without PDFs for now.

**Closed by mgedmin** 2017-12-14 08:59 UTC
Labels: help wanted

**Comment by icemac** [comment] 2017-12-15 07:05
@mgedmin Thank you for your investigation and fixing this issue.
